version: '3.8'
services:
  soulvent-main:
    build:
      context: ..  # This tells Docker to look in the parent directory
      dockerfile: Dockerfile  # This specifies the Dockerfile name
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    env_file:
      - ../.env
    ports:
      - "5432:5432"
