version: '3.8'
services:
  soulvent-main:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: postgres:13
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
