services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod  # Use production dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" 
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

volumes:
  redis-data: