# SoulVent main service configuration
server:
  port: 8080
database:
  postgres:
    host: localhost
    port: 5432
    user: soulvent
    password: password
    dbname: soulvent_db
elasticsearch:
  url: http://localhost:9200
jwt:
  secret: your_jwt_secret
rate_limit:
  requests_per_minute: 100
s3:
  bucket: soulvent-images
  region: us-east-1
