openapi: 3.0.0
info:
  title: SoulVent Main Service API
  version: 1.0.0
paths:
  /posts:
    post:
      summary: Create a post
      responses:
        '201':
          description: Created
    get:
      summary: Get feed
      responses:
        '200':
          description: OK
  /users/{id}:
    get:
      summary: Get user profile
      responses:
        '200':
          description: OK
  /comments:
    post:
      summary: Add a comment
      responses:
        '201':
          description: Created
